# Generated by Django 5.2.6 on 2025-09-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="bike_type",
            field=models.CharField(default="Rolling", max_length=50),
        ),
        migrations.AddField(
            model_name="event",
            name="run_type",
            field=models.CharField(default="Flat", max_length=50),
        ),
        migrations.AddField(
            model_name="event",
            name="swim_type",
            field=models.CharField(default="Lake", max_length=50),
        ),
        migrations.AddField(
            model_name="event",
            name="temp_high",
            field=models.IntegerField(default=23),
        ),
        migrations.AddField(
            model_name="event",
            name="temp_water",
            field=models.IntegerField(default=18),
        ),
    ]
