# Generated by Django 5.2.6 on 2025-09-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_event_bike_type_event_run_type_event_swim_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendedRace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="recommended/")),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="sponsors/")),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
